version: '3'

services:
  streaming:
    image: streaming
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
